version: '3.8'
services:
  dreamcar-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dreamcar-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: dreamcar
      POSTGRES_HOST_AUTH_METHOD: trust
